<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\NovaLauncher.App\NovaLauncher.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\src\NovaLauncher.App\App.axaml" Link="App.axaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\App.axaml.cs" Link="App.axaml.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\AvaloniaThemeHost.cs" Link="AvaloniaThemeHost.cs" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\Assets\NovaLauncher.ico" Link="Assets\NovaLauncher.ico" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\MainWindow.axaml" Link="MainWindow.axaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\Views\Pages\HomeView.axaml" Link="Views\Pages\HomeView.axaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\Views\Pages\LibraryView.axaml" Link="Views\Pages\LibraryView.axaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\Views\Pages\GameDetailsView.axaml" Link="Views\Pages\GameDetailsView.axaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\Views\Pages\TransfersView.axaml" Link="Views\Pages\TransfersView.axaml" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\NovaLauncher.App\Views\Pages\SettingsView.axaml" Link="Views\Pages\SettingsView.axaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
