namespace NovaLauncher.Services.Assets;

/// <summary>
/// Identifies a managed directory within a game's NovaLauncher
/// asset structure.
///
/// Folder names should be resolved through <see cref="AssetPaths"/>
/// rather than manually using Path.Combine throughout the application.
/// </summary>
public enum AssetFolder
{
    /// <summary>
    /// The root directory for a specific game's assets.
    ///
    /// Example:
    /// Assets/GameName_GameId/
    /// </summary>
    GameRoot,

    /// <summary>
    /// Root directory containing all artwork associated with the game.
    ///
    /// Example:
    /// Assets/GameName_GameId/Artwork/
    /// </summary>
    Artwork,

    /// <summary>
    /// Original artwork downloaded or imported from providers.
    ///
    /// These files should be preserved without modification.
    ///
    /// Example:
    /// Assets/GameName_GameId/Artwork/Original/
    /// </summary>
    ArtworkOriginal,

    /// <summary>
    /// Artwork generated by NovaLauncher from an original source.
    ///
    /// Examples include normalized covers, heroes, thumbnails,
    /// and blurred backgrounds.
    ///
    /// Example:
    /// Assets/GameName_GameId/Artwork/Generated/
    /// </summary>
    ArtworkGenerated,

    /// <summary>
    /// Artwork manually supplied by the user.
    ///
    /// Example:
    /// Assets/GameName_GameId/Artwork/Custom/
    /// </summary>
    ArtworkCustom,

    /// <summary>
    /// Contains the artwork currently selected for display.
    ///
    /// The UI should normally read artwork from this directory
    /// instead of directly reading provider or generated files.
    ///
    /// Example:
    /// Assets/GameName_GameId/Artwork/Active/
    /// </summary>
    ArtworkActive,

    /// <summary>
    /// Save-game information, save manifests, backups,
    /// and synchronization metadata.
    ///
    /// Example:
    /// Assets/GameName_GameId/Saves/
    /// </summary>
    Saves,

    /// <summary>
    /// Screenshots associated with the game.
    ///
    /// Example:
    /// Assets/GameName_GameId/Screenshots/
    /// </summary>
    Screenshots,

    /// <summary>
    /// Videos, trailers, gameplay clips, and animated previews.
    ///
    /// Example:
    /// Assets/GameName_GameId/Videos/
    /// </summary>
    Videos,

    /// <summary>
    /// Game icons and launcher-specific icon variants.
    ///
    /// Example:
    /// Assets/GameName_GameId/Icons/
    /// </summary>
    Icons,

    /// <summary>
    /// Mod metadata, manifests, thumbnails, and other
    /// NovaLauncher-managed mod information.
    ///
    /// Example:
    /// Assets/GameName_GameId/Mods/
    /// </summary>
    Mods,

    /// <summary>
    /// Re-creatable cached data associated with the game.
    ///
    /// Files stored here may be deleted and regenerated safely.
    ///
    /// Example:
    /// Assets/GameName_GameId/Cache/
    /// </summary>
    Cache,

    /// <summary>
    /// Temporary working files used during downloads,
    /// imports, conversions, and other asset operations.
    ///
    /// Example:
    /// Assets/GameName_GameId/Temp/
    /// </summary>
    Temp
}